#!/bin/sh -e

#DEBHELPER#

error()
{
    RET=$?
    MSG=$1
    echo "E: $MSG";
    exit $RET
}

case "$1" in
    configure)

        # We've moved to use /etc/default/grub.d/ instead, drop previous
        # entry to unmangle the /etc/default/grub.
        if [ -e /etc/default/grub ]; then
            sed -i 's%GRUB_THEME=/boot/grub/themes/breeze/theme.txt%%g' /etc/default/grub
        fi

        # Update to pick up theme setting from grub.d/
        if [ -e /boot/grub/grub.cfg ] && which update-grub2 >/dev/null 2>&1; then
            update-grub2 || error "Failed to update-grub2"
        fi

        ;;

    abort-upgrade|abort-deconfigure|abort-remove)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac

exit 0
